import { QUESTION_DIFFICULTIES, QUESTION_TYPES } from "./constants";

export const QUESTION_DIFFICULTIES_LABELS = {
    [ QUESTION_DIFFICULTIES.EASY ]: 'Easy',
    [ QUESTION_DIFFICULTIES.MEDIUM ]: 'Medium',
    [ QUESTION_DIFFICULTIES.HARD ]: 'Hard'
};

export const QUESTION_TYPES_LABELS = {
    [ QUESTION_TYPES.ANY ]: 'Any',
    [ QUESTION_TYPES.SINGLE ]: 'True / False',
    [ QUESTION_TYPES.MULTIPLE ]: 'Multiple Choice',
}